In [5]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [6]:
# Chargement du BN
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

Nombre_de_Samples = 200
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)

dfargs.to_csv("building-input.csv", index=False)
dfHPXML.to_csv("building-test.csv", index=False)

dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfargs)
display(dfHPXML)

Nombre d'attributs HPXML:  66

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Infiltration,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,...,Piscine_Minuterie,An_Construction,Source_Energie_Chauf,Chauffage_Logement,Climatisation,Spa_Presence,Spa_Logement,Spa_Saison,Spa_Utilisation_SaisonChaude,Spa_Utilisation_SaisonFroide
0,1,1,Not Applicable,None,10 ACH50,"Single, Clear, Metal",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Aucun,[1960 - 1970),Electricite,Plinthes électriques,"Fenêtre, mobile, portable",Non,Aucun,Aucun,Aucun,Aucun
1,1,16,Middle,Bottom,4 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,Aucun,[2000 - 2010),Electricite,Plinthes électriques,Aucune,Non,Aucun,Aucun,Aucun,Aucun
2,1,1,Not Applicable,None,3 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,Aucun,[2010 - 2020),Electricite,Plinthes électriques,Aucune,Non,Aucun,Aucun,Aucun,Aucun
3,3,3,Not Applicable,Middle,7 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,...,Aucun,< 1950,Electricite,Plinthes électriques,Aucune,Non,Aucun,Aucun,Aucun,Aucun
4,1,1,Not Applicable,None,5 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,...,Non,[1980 - 1990),Electricite,Plinthes électriques,"Fenêtre, mobile, portable",Non,Aucun,Aucun,Aucun,Aucun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,67,Middle,Bottom,3 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,Aucun,[2000 - 2010),Electricite,Plinthes électriques,"Fenêtre, mobile, portable",Non,Aucun,Aucun,Aucun,Aucun
196,1,2,Left,None,1 ACH50,"Triple, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,Aucun,[2010 - 2020),Electricite,Thermopompe,Centrale,Non,Aucun,Aucun,Aucun,Aucun
197,1,1,Not Applicable,None,6 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Non,[1960 - 1970),Electricite,Plinthes électriques,"Fenêtre, mobile, portable",Non,Aucun,Aucun,Aucun,Aucun
198,14,116,Right,Middle,4 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R14.4, interior",None,...,Aucun,[1970 - 1980),Electricite,Thermopompe,Centrale,Non,Aucun,Aucun,Aucun,Aucun
199,2,2,Not Applicable,Bottom,3 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,...,Aucun,[1960 - 1970),Bi-energie,Thermopompe,Centrale,Non,Aucun,Aucun,Aucun,Aucun

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,heat_pump_backup_fuel,heat_pump_backup_heating_efficiency,geothermal_loop_configuration,cooling_system_type,cooling_system_cooling_compressor_type,overhangs_front_depth,overhangs_front_distance_to_top_of_window,heat_pump_is_ducted,heat_pump_cooling_compressor_type,heat_pump_compressor_lockout_temp
0,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1698,0.5,1965,...,electricity,1.0,none,central air conditioner,single stage,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,16,apartment unit,8,0.5556,1138,0.5,2005,...,electricity,1.0,none,none,None,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1228,0.5,2015,...,electricity,1.0,none,none,None,NaN,NaN,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,3,apartment unit,8,0.5556,1138,0.5,1940,...,electricity,1.0,none,none,None,10.0,1.0,NaN,NaN,NaN
4,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,0.5,1985,...,electricity,1.0,none,central air conditioner,single stage,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,67,apartment unit,8,0.5556,2115,0.5,2005,...,electricity,1.0,none,central air conditioner,single stage,NaN,NaN,NaN,NaN,NaN
196,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,2,single-family attached,8,0.5556,750,0.5,2015,...,electricity,1.0,none,none,NaN,NaN,NaN,true,single stage,NaN
197,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,750,0.5,1965,...,electricity,1.0,none,central air conditioner,single stage,NaN,NaN,NaN,NaN,NaN
198,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,116,apartment unit,8,0.5556,1138,0.5,1975,...,electricity,1.0,none,none,NaN,NaN,NaN,true,single stage,NaN
199,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,2,apartment unit,8,0.5556,1682,0.5,1965,...,fuel oil,0.8,none,none,NaN,10.0,1.0,true,single stage,10.4