In [5]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, BuildstockBachArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [6]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 10
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBachArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire


MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)
display(pd.DataFrame(lst_dct_args))
dfHPXML = pd.DataFrame(lst_dct_HPXML)
dfHPXML.to_csv("building-test.csv", index=False)
#dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfHPXML)

Nombre d'attributs HPXML:  43

,geometry_building_num_units,Infiltration,Windows,Insulation_Wall,Insulation_Ceiling,Insulation_Foundation_Wall,Geometry_Wall_Exterior_Finish,geometry attic type,HVAC_Has_Shared_System,Territoire_HQ,Type_Logement,Mode_Occupation,Presence_Garage,Nombre_Etages,Presence_SousSol,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,An_Construction,Source_Energie_Chauf
0,1,4 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,Montmorency,Maison individuelle,Locataire,Garage non chauffé,Deux étages,Sous sol 6 pied,9,5 et plus,[2500 - 3000),[2000 - 2010),Electricite
1,1,5 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,Vented Attic,None,Laurentides,Maison individuelle,Proprietaire,Pas de Garage,Un étage,Vide sanitaire moins 6 pieds,4,1,[1000 - 1500),[2010 - 2020),Electricite
2,1,6 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,Laurentides,Maison individuelle,Proprietaire,Pas de Garage,Trois étages et plus,Sous sol 6 pied,6,5 et plus,[2000 - 2500),[1970 - 1980),Electricite
3,2,5 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,Montréal,Duplex,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,5,5 et plus,[500 - 1000),[1970 - 1980),Electricite
4,1,8 ACH50,"Double, Low-E, Non-metal, Air, M-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,Laurentides,Maison individuelle,Proprietaire,Pas de Garage,Deux étages,Sous sol 6 pied,5,2,[500 - 1000),[2000 - 2010),Electricite
5,3,5 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,Vented Attic,None,Laurentides,Triplex,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,3,5 et plus,[500 - 1000),[1950 - 1960),Electricite
6,2,4 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,Richelieu,Duplex,Proprietaire,Pas de Garage,Trois étages et plus,Aucun Sous-sol ou vide sanitaire,6,1,[1000 - 1500),[1970 - 1980),Electricite
7,1,7 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,None,Montmorency,Maison individuelle,Proprietaire,Pas de Garage,Trois étages et plus,Sous sol 6 pied,11,2,[3000 - 3500),[1960 - 1970),Electricite
8,1,15 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,None,Montréal,Maison individuelle,Proprietaire,Pas de Garage,Un étage,Sous sol 6 pied,5,2,[1000 - 1500),[1950 - 1960),Bois
9,8,3 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,Vented Attic,None,Laurentides,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,4,[500 - 1000),[1990 - 2000),Electricite

,geometry_building_num_units,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,wall_color,geometry_attic_type,geometry_roof_type,geometry_roof_pitch,air_leakage_units,air_leakage_house_pressure,air_leakage_value,air_leakage_type,site_shielding_of_home,rim_joist_assembly_r
0,1,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,single-family detached,8,1.8000,2678,0.5,2005,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
1,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1228,0.5,2015,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
2,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.5,1975,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
3,2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1975,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,0.0
4,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,750,0.5,2005,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
5,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1955,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,0.0
6,2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.5,1975,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,0.0
7,1,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,single-family detached,8,1.8000,3250,0.5,1965,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
8,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1228,0.5,1955,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,2.5
9,8,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1995,...,medium,FlatRoof,gable,6:12,ACH,50,5,unit exterior only,normal,0.0