In [1]:
import os
import sys
import pandas as pd
import dtale
from utils.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [2]:
# Chargement du BN
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

Nombre_de_Samples = 200
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)

dfargs.to_csv("building-input.csv", index=False)
dfHPXML.to_csv("building-test.csv", index=False)

dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfargs)
display(dfHPXML)

Nombre d'attributs HPXML:  82

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Infiltration,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,...,Spa_Presence,Spa_Logement,Spa_Saison,Spa_Utilisation_SaisonChaude,Spa_Utilisation_SaisonFroide,An_Construction,Source_Energie_Chauf,ChaufEau_ChaufType,Chauffage_Logement,Climatisation
0,12,116,Left,Bottom,10 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1950 - 1960),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable"
1,3,3,Not Applicable,Middle,7 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,< 1950,Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable"
2,1,1,Not Applicable,None,3 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[2000 - 2010),Electricite,Electrique,Thermopompe,Centrale
3,11,116,Middle,Middle,2 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1990 - 2000),Electricite,Electrique,"Unités convecteurs, plancher ou plafond radiant",Aucune
4,1,1,Not Applicable,None,7 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1950 - 1960),Electricite,Electrique,Plinthes électriques,Murale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,Not Applicable,None,5 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,...,Oui,Exterieur,Pas utilisé,Aucun,Aucun,[1970 - 1980),Bois,Electrique,Fournaise ou poêle à bois,Aucune
196,1,1,Not Applicable,None,8 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1960 - 1970),Bi-energie,Electrique,Thermopompe,Centrale
197,1,1,Not Applicable,None,7 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1960 - 1970),Electricite,Electrique,Système central à eau chaude,Aucune
198,1,1,Not Applicable,None,5 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,Oui,Exterieur,Toute_Saison,Constant,Constant,[2010 - 2020),Electricite,Electrique,Système central à air chaud,Aucune
199,1,1,Not Applicable,None,10 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,...,Non,Aucun,Aucun,Aucun,Aucun,[1960 - 1970),Bi-energie,Electrique,Thermopompe,Centrale

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,water_heater_type,water_heater_location,overhangs_front_depth,overhangs_front_distance_to_top_of_window,water_heater_tank_volume,heat_pump_is_ducted,heat_pump_cooling_compressor_type,misc_plug_loads_vehicle_annual_kwh,misc_plug_loads_vehicle_usage_multiplier,heat_pump_compressor_lockout_temp
0,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,116,apartment unit,8,0.5556,750,0.5,1955,...,storage water heater,conditioned space,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,3,apartment unit,8,0.5556,1138,0.5,1940,...,storage water heater,conditioned space,10.0,1.0,40.0,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,750,0.5,2005,...,storage water heater,conditioned space,NaN,NaN,70.0,true,single stage,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,116,apartment unit,8,0.5556,1138,0.5,1995,...,storage water heater,conditioned space,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN
4,2020s_CAN_QC_Saguenay-Bagotville.AP-CFB.Bagotv...,True,-5,1,single-family detached,8,1.8000,2179,0.5,1955,...,storage water heater,conditioned space,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,1698,0.5,1975,...,storage water heater,conditioned space,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,3750,0.5,1965,...,storage water heater,conditioned space,NaN,NaN,60.0,true,single stage,NaN,NaN,10.4
197,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1698,0.5,1965,...,storage water heater,conditioned space,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN
198,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,1228,0.5,2015,...,storage water heater,conditioned space,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN
199,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,2678,0.5,1965,...,storage water heater,conditioned space,NaN,NaN,NaN,true,single stage,NaN,NaN,10.4

In [5]:
dtale.show(dfargs)

In [4]:
dtale.show(dfHPXML)