In [21]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, MapHPXML

PROJECT_DIR = os.getcwd()

In [22]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 10
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
display(df1)
pd.DataFrame(lst_dct_HPXML)

Nombre d'attributs HPXML:  191

,Territoire_HQ,Type_Logement,Mode_Occupation,Presence_Garage,Nombre_Etages,Presence_SousSol,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,An_Construction,Source_Energie_Chauf
0,Montmorency,Maison individuelle,Proprietaire,Garage chauffé à électricité,Deux étages,Sous sol 6 pied,6,2,[1000 - 1500),[2000 - 2010),Bois
1,Montmorency,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,1,[1000 - 1500),[2010 - 2020),Electricite
2,Richelieu,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,5,1,[1000 - 1500),[1960 - 1970),Electricite
3,Laurentides,Maison individuelle,Proprietaire,Garage non chauffé,Deux étages,Sous sol 6 pied,6,5 et plus,[1500 - 2000),[2010 - 2020),Electricite
4,Montmorency,Collective,Proprietaire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,3,1,[500 - 1000),[2000 - 2010),Electricite
5,Montréal,Collective,Proprietaire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,2,[500 - 1000),[1950 - 1960),Electricite
6,Richelieu,Maison individuelle,Proprietaire,Pas de Garage,Deux étages,Sous sol 6 pied,6,3,[2500 - 3000),[2010 - 2020),Electricite
7,Montréal,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,5,2,[1000 - 1500),[1970 - 1980),Electricite
8,Laurentides,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,2,[1000 - 1500),[2000 - 2010),Electricite
9,Montmorency,Maison individuelle,Proprietaire,Pas de Garage,Trois étages et plus,Sous sol 6 pied,10,4,[1000 - 1500),[1990 - 2000),Electricite

,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,geometry_unit_num_bedrooms,geometry_unit_num_occupants,geometry_garage_width,geometry_garage_depth,...,hot_water_distribution_system_type,slab_perimeter_insulation_r,pv_system_2_array_azimuth,mech_vent_sensible_recovery_efficiency,window_aspect_ratio,cooling_system_type,misc_plug_loads_vehicle_present,mech_vent_2_flow_rate,window_right_wwr,lighting_interior_fraction_cfl
0,single-family detached,8,1.8000,1228,0.5,2005,3,2,24,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
1,apartment unit,8,0.5556,1138,0.5,2015,2,1,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
2,apartment unit,8,0.5556,1138,0.5,1965,3,1,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
3,single-family detached,8,1.8000,1698,0.5,2015,3,5,24,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
4,apartment unit,8,0.5556,750,0.5,2005,2,1,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
5,apartment unit,8,0.5556,750,0.5,1955,2,2,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
6,single-family detached,8,1.8000,2678,0.5,2015,3,3,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
7,apartment unit,8,0.5556,1138,0.5,1975,3,2,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
8,apartment unit,8,0.5556,1138,0.5,2005,2,2,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1
9,single-family detached,8,1.8000,1228,0.5,1995,5,4,0,24,...,Standard,0,180,0.72,1.333,central air conditioner,false,110,0.18,0.1