In [1]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, BuildstockBachArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [ ]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 100
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBachArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire


MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)
display(pd.DataFrame(lst_dct_args))
dfHPXML = pd.DataFrame(lst_dct_HPXML)
dfHPXML.to_csv("building-test.csv", index=False)
dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfHPXML)

Nombre d'attributs HPXML:  49

,geometry_building_num_units,Infiltration,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,geometry attic type,HVAC Has Shared System,HVAC Heating Efficiency,...,Mode_Occupation,An_Construction,Source_Energie_Chauf,Chauffage_Logement,Nombre_Etages,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,Presence_SousSol,Presence_Garage
0,3,6 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,[1950 - 1960),Electricite,Plinthes électriques,Un étage,4,2,[500 - 1000),Aucun Sous-sol ou vide sanitaire,Pas de Garage
1,25,3 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,< 1950,Electricite,Plinthes électriques,Un étage,3,3,[500 - 1000),Aucun Sous-sol ou vide sanitaire,Pas de Garage
2,1,3 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1970 - 1980),Electricite,Plinthes électriques,Deux étages,5,2,[3000 - 3500),Sous sol 6 pied,Pas de Garage
3,1,5 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1980 - 1990),Electricite,Plinthes électriques,Deux étages,10,3,[1500 - 2000),Sous sol 6 pied,Pas de Garage
4,8,6 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,[1950 - 1960),Electricite,Plinthes électriques,Un étage,3,5 et plus,[1000 - 1500),Aucun Sous-sol ou vide sanitaire,Pas de Garage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,6 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1950 - 1960),Electricite,Plinthes électriques,Trois étages et plus,9,5 et plus,[2000 - 2500),Sous sol 6 pied,Garage chauffé à électricité
96,5,4 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,[1980 - 1990),Electricite,Plinthes électriques,Un étage,4,1,[500 - 1000),Aucun Sous-sol ou vide sanitaire,Pas de Garage
97,3,2 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,[1980 - 1990),Electricite,Plinthes électriques,Un étage,3,1,[3000 - 3500),Aucun Sous-sol ou vide sanitaire,Pas de Garage
98,1,7 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1980 - 1990),Electricite,Plinthes électriques,Deux étages,6,1,[2000 - 2500),Sous sol 6 pied,Garage chauffé à électricité
99,1,2 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[2010 - 2020),Electricite,Plinthes électriques,Un étage,4,1,[500 - 1000),Aucun Sous-sol ou vide sanitaire,Garage non chauffé

,geometry_building_num_units,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,air_leakage_value,air_leakage_type,site_shielding_of_home,rim_joist_assembly_r,geometry_unit_left_wall_is_adiabatic,geometry_unit_right_wall_is_adiabatic,geometry_unit_front_wall_is_adiabatic,geometry_unit_back_wall_is_adiabatic,cooling_system_type,cooling_system_cooling_compressor_type
0,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1955,...,5,unit exterior only,normal,0.0,False,False,False,False,none,None
1,25,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1940,...,5,unit exterior only,normal,0.0,False,False,False,False,central air conditioner,single stage
2,1,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,single-family detached,8,1.8000,3250,0.5,1975,...,5,unit exterior only,normal,2.5,False,False,False,False,central air conditioner,single stage
3,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1698,0.5,1985,...,5,unit exterior only,normal,2.5,False,False,False,False,none,None
4,8,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.5,1955,...,5,unit exterior only,normal,0.0,False,False,False,False,central air conditioner,single stage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.5,1955,...,5,unit exterior only,normal,2.5,False,False,False,False,mini-split,variable speed
96,5,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1985,...,5,unit exterior only,normal,0.0,False,False,False,False,mini-split,variable speed
97,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,3250,0.5,1985,...,5,unit exterior only,normal,0.0,False,False,False,False,none,None
98,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.5,1985,...,5,unit exterior only,normal,2.5,False,False,False,False,central air conditioner,single stage
99,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,750,0.5,2015,...,5,unit exterior only,normal,0.0,False,False,False,False,none,None