In [2]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, BuildstockBachArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [3]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 10
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBachArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire


MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)
display(pd.DataFrame(lst_dct_args))
dfHPXML = pd.DataFrame(lst_dct_HPXML)
dfHPXML.to_csv("building-test.csv", index=False)
display(dfHPXML)

Nombre d'attributs HPXML:  194

,geometry_foundation_type,Territoire_HQ,Type_Logement,Mode_Occupation,Presence_Garage,Nombre_Etages,Presence_SousSol,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,An_Construction,Source_Energie_Chauf
0,Slab,Montréal,Collective,Proprietaire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,2,[1000 - 1500),[1970 - 1980),Electricite
1,Heated Basement,Laurentides,Maison individuelle,Proprietaire,Garage chauffé à électricité,Deux étages,Sous sol 6 pied,6,2,[1000 - 1500),[1960 - 1970),Bi-energie
2,Heated Basement,Richelieu,Maison individuelle,Proprietaire,Garage chauffé à électricité,Trois étages et plus,Sous sol 6 pied,12,5 et plus,>= 5000,[2000 - 2010),Electricite
3,Slab,Laurentides,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,3,2,[500 - 1000),[1990 - 2000),Electricite
4,Heated Basement,Laurentides,Maison individuelle,Proprietaire,Garage chauffé à électricité,Trois étages et plus,Sous sol 6 pied,8,2,[1500 - 2000),< 1950,Electricite
5,Slab,Richelieu,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,3,2,[500 - 1000),[1970 - 1980),Electricite
6,Slab,Montréal,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,2,[1000 - 1500),[1950 - 1960),Gaz naturel
7,Heated Basement,Montréal,Maison individuelle,Proprietaire,Garage chauffé à électricité,Trois étages et plus,Sous sol 6 pied,12,3,[1500 - 2000),[1990 - 2000),Electricite
8,Heated Basement,Laurentides,Maison individuelle,Proprietaire,Garage chauffé à électricité,Deux étages,Sous sol 6 pied,10,3,[2000 - 2500),[2000 - 2010),Electricite
9,Slab,Montréal,Maison individuelle,Proprietaire,Garage chauffé à électricité,Deux étages,Sous sol 6 pied,7,2,[500 - 1000),[1980 - 1990),Electricite

,geometry_foundation_type,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,pv_system_2_array_azimuth,slab_perimeter_insulation_r,clothes_dryer_present,pv_system_max_power_output,heat_pump_backup_type,dwhr_efficiency,cooking_range_oven_fuel_type,neighbor_front_distance,misc_fuel_loads_fireplace_present,mech_vent_2_hours_in_operation
0,Slab,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.5,1975,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
1,Heated Basement,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1228,0.5,1965,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
2,Heated Basement,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,5587,0.5,2005,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
3,Slab,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1995,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
4,Heated Basement,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1698,0.5,1940,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
5,Slab,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.5,1975,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
6,Slab,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.5,1955,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
7,Heated Basement,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,1698,0.5,1995,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
8,Heated Basement,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.5,2005,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24
9,Slab,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,750,0.5,1985,...,180,0,true,4000,integrated,0.55,natural gas,0,false,24