In [1]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [2]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 100
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire


MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)
display(pd.DataFrame(lst_dct_args))
dfHPXML = pd.DataFrame(lst_dct_HPXML)
dfHPXML.to_csv("building-test.csv", index=False)
dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfHPXML)

Nombre d'attributs HPXML:  66

,geometry_building_num_units,Infiltration,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,geometry attic type,HVAC Has Shared System,HVAC Heating Efficiency,...,Mode_Occupation,An_Construction,Source_Energie_Chauf,Chauffage_Logement,Nombre_Etages,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,Presence_SousSol,Presence_Garage
0,3,5 ACH50,"Double, Clear, Metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,[1970 - 1980),Electricite,Plinthes électriques,Un étage,2,1,[1000 - 1500),Aucun Sous-sol ou vide sanitaire,Pas de Garage
1,1,4 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1950 - 1960),Electricite,Plinthes électriques,Deux étages,11,5 et plus,[2000 - 2500),Sous sol 6 pied,Pas de Garage
2,1,3 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Fuel Boiler, 72% AFUE",...,Locataire,[1990 - 2000),Bois,Fournaise ou poêle à bois,Trois étages et plus,12,2,[3500 - 4000),Sous sol 6 pied,Pas de Garage
3,49,3 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,Vented Attic,None,"Electric Wall Furnace, 100% AFUE",...,Locataire,[2010 - 2020),Electricite,"Unités convecteurs, plancher ou plafond radiant",Un étage,3,1,[1000 - 1500),Aucun Sous-sol ou vide sanitaire,Pas de Garage
4,1,4 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,None,"Electric Wall Furnace, 100% AFUE",...,Proprietaire,[1990 - 2000),Electricite,"Unités convecteurs, plancher ou plafond radiant",Deux étages,8,2,[2000 - 2500),Aucun Sous-sol ou vide sanitaire,Garage non chauffé
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,6 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,< 1950,Electricite,Plinthes électriques,Un étage,4,5 et plus,[1000 - 1500),Aucun Sous-sol ou vide sanitaire,Garage chauffé à électricité
96,5,8 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,< 1950,Electricite,Plinthes électriques,Un étage,3,1,[1000 - 1500),Aucun Sous-sol ou vide sanitaire,Pas de Garage
97,1,6 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Proprietaire,[1960 - 1970),Electricite,Plinthes électriques,Trois étages et plus,7,3,[2500 - 3000),Sous sol 6 pied,Pas de Garage
98,3,10 ACH50,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,None,"Electric Baseboard, 100% Efficiency",...,Locataire,< 1950,Electricite,Plinthes électriques,Un étage,3,1,[500 - 1000),Aucun Sous-sol ou vide sanitaire,Pas de Garage
99,1,5 ACH50,"Double, Clear, Non-metal, Air",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,Vented Attic,None,"ASHP, SEER 15, 8.5 HSPF",...,Locataire,[1970 - 1980),Electricite,Thermopompe,Un étage,5,4,[1 - 500),Sous sol 6 pied,Garage chauffé à électricité

,geometry_building_num_units,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,...,heat_pump_fraction_cool_load_served,heat_pump_backup_use_existing_system,heat_pump_backup_type,heat_pump_backup_fuel,heat_pump_backup_heating_efficiency,geothermal_loop_configuration,cooling_system_type,cooling_system_cooling_compressor_type,heat_pump_is_ducted,heat_pump_cooling_compressor_type
0,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.50,1975,...,1.0,false,none,electricity,1.0,none,central air conditioner,single stage,NaN,NaN
1,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.50,1955,...,1.0,false,none,electricity,1.0,none,none,None,NaN,NaN
2,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,3750,0.50,1995,...,1.0,false,none,electricity,1.0,none,mini-split,variable speed,NaN,NaN
3,49,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.50,2015,...,1.0,false,none,electricity,1.0,none,central air conditioner,single stage,NaN,NaN
4,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2179,0.50,1995,...,1.0,false,none,electricity,1.0,none,none,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.50,1940,...,1.0,false,none,electricity,1.0,none,central air conditioner,single stage,NaN,NaN
96,5,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,1138,0.50,1940,...,1.0,false,none,electricity,1.0,none,central air conditioner,single stage,NaN,NaN
97,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,2678,0.50,1965,...,1.0,false,none,electricity,1.0,none,mini-split,variable speed,NaN,NaN
98,3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,apartment unit,8,0.5556,750,0.50,1940,...,1.0,false,none,electricity,1.0,none,mini-split,variable speed,NaN,NaN
99,1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,single-family detached,8,1.8000,298,0.75,1975,...,1.0,false,integrated,electricity,1.0,none,none,NaN,true,single stage