In [1]:
import os
import sys
import pandas as pd

from utils.Sampler import Sampler, MapHPXML

PROJECT_DIR = os.getcwd()

In [2]:
# Load the Bayesian Network from the saved file
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# Display the Bayesian Network - Avant enregistrement
#gnb.showInference(InsClsSampler.bn,evs={},size = '30')

Nombre_de_Samples = 10
Evidence = {}#"Type_Logement": "Collective",
            #"Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Fait un échantillonage - Avant enregistrement
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement

#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
display(df1)
dfHPXML = pd.DataFrame(lst_dct_HPXML)
dfHPXML.to_csv("building-test.csv", index=False)
display(dfHPXML)

Nombre d'attributs HPXML:  192

,Territoire_HQ,Type_Logement,Mode_Occupation,Presence_Garage,Nombre_Etages,Presence_SousSol,Nombre_Pieces,Nombre_Personnes,Superficie_Totale,An_Construction,Source_Energie_Chauf
0,Richelieu,Duplex,Locataire,Pas de Garage,Deux étages,Aucun Sous-sol ou vide sanitaire,12,1,[1000 - 1500),[1990 - 2000),Electricite
1,Montmorency,Maison individuelle,Proprietaire,Garage non chauffé,Deux étages,Sous sol 6 pied,2,1,[500 - 1000),< 1950,Mazout
2,Montréal,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,3,1,[1000 - 1500),[1970 - 1980),Electricite
3,Montmorency,Maison individuelle,Proprietaire,Garage non chauffé,Deux étages,Sous sol 6 pied,5,2,[500 - 1000),[1980 - 1990),Electricite
4,Montréal,Collective,Proprietaire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,3,[500 - 1000),[2000 - 2010),Electricite
5,Montmorency,Maison individuelle,Proprietaire,Pas de Garage,Trois étages et plus,Sous sol 6 pied,12,2,[1500 - 2000),[1980 - 1990),Electricite
6,Montmorency,Collective,Locataire,Pas de Garage,Un étage,Aucun Sous-sol ou vide sanitaire,4,1,[1000 - 1500),[2010 - 2020),Electricite
7,Richelieu,Maison individuelle,Proprietaire,Pas de Garage,Deux étages,Sous sol 6 pied,4,1,[500 - 1000),[1960 - 1970),Bi-energie
8,Montmorency,Duplex,Locataire,Pas de Garage,Trois étages et plus,Aucun Sous-sol ou vide sanitaire,5,1,[1000 - 1500),>= 2020,Electricite
9,Montmorency,Maison en rangee,Proprietaire,Garage chauffé à électricité,Trois étages et plus,Sous sol 6 pied,4,2,[500 - 1000),>= 2020,Electricite

,weather_station_epw_filepath,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,geometry_garage_protrusion,year_built,geometry_unit_num_bedrooms,geometry_unit_num_occupants,geometry_garage_width,...,mech_vent_2_flow_rate,geometry_roof_pitch,pv_system_present,pv_system_2_max_power_output,heat_pump_fraction_cool_load_served,cooling_system_type,cooling_system_fraction_cool_load_served,skylight_shgc,dishwasher_efficiency_type,pool_heater_type
0,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,apartment unit,8,0.5556,1138,0.5,1995,6,1,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
1,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,single-family detached,8,1.8000,750,0.5,1940,1,1,24,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,apartment unit,8,0.5556,1138,0.5,1975,2,1,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
3,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,single-family detached,8,1.8000,750,0.5,1985,3,2,24,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
4,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,apartment unit,8,0.5556,750,0.5,2005,2,3,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
5,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,single-family detached,8,1.8000,1698,0.5,1985,6,2,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
6,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,apartment unit,8,0.5556,1138,0.5,2015,2,1,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
7,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,single-family detached,8,1.8000,750,0.5,1965,2,1,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
8,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,apartment unit,8,0.5556,1138,0.5,2020,3,1,0,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none
9,2050s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,single-family attached,8,0.5556,750,0.5,2020,2,2,24,...,110,6:12,false,4000,1,central air conditioner,1,0.45,RatedAnnualkWh,none