In [5]:
import os
import sys
import pandas as pd
import dtale
from utils.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

PROJECT_DIR = os.getcwd()

In [6]:
# Chargement du BN
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

Nombre_de_Samples = 1000
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)

dfargs.to_csv("building-input.csv", index=False)
dfHPXML.to_csv("building-test.csv", index=False)

dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfargs)
display(dfHPXML)

Nombre d'attributs HPXML:  131

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,geometry attic type,...,Eclairage_LED,Type_Batiment,An_Construction,Infiltration,An_ConstructionCode,Source_Energie_Chauf,Cuisiniere_Energie,Chauffage_Logement,Climatisation,ChaufEau_ChaufType
0,1,1,Not Applicable,None,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14.5,QC_R19.6,"QC_Wall-R10.1, interior",None,Vented Attic,...,25 à 50 %,Maison,< 1950,Option=10 ACH50,< 1946,Electricite,Electrique,Système central à air chaud,Centrale,Electrique
1,35,326,Middle,Middle,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,...,0%,Collective,< 1950,Option=15 ACH50,< 1946,Electricite,Electrique,Plinthes électriques,Aucune,Electrique
2,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,1 à 24 %,Maison,[1980 - 1990),Option=5 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique
3,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,Plus de 50 %,Maison,[2000 - 2010),Option=7 ACH50,[1986 - 2013),Electricite,Electrique,Système central à eau chaude,Aucune,Electrique
4,3,3,Not Applicable,Top,"Double, Clear, Metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,Vented Attic,...,Plus de 50 %,Plex,< 1950,Option=4 ACH50,< 1946,Electricite,Electrique,Thermopompe murale et Plinthes électriques,Murale,Electrique
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,6,Left,Top,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R14.4, interior",None,Vented Attic,...,25 à 50 %,Collective,[1970 - 1980),Option=4 ACH50,[1946 - 1971),Electricite,Electrique,Plinthes électriques,Murale,Electrique
996,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R14.5,QC_R19.6,"QC_Wall-R10.1, interior",None,Vented Attic,...,Plus de 50 %,Maison,< 1950,Option=10 ACH50,< 1946,Bois,Electrique,Fournaise ou poêle à bois,"Fenêtre, mobile, portable",Electrique
997,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R14.5,QC_R19.6,"QC_Wall-R10.1, interior",None,Vented Attic,...,Plus de 50 %,Maison,< 1950,Option=8 ACH50,< 1946,Mazout,Aucun,Système central à eau chaude,Centrale,Electrique
998,1,1,Not Applicable,None,"Double, Clear, Metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,Ne sait pas,Maison,[2000 - 2010),Option=7 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,Murale,Gaz Naturel
999,1,1,Not Applicable,None,"Double, Clear, Metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,Vented Attic,...,1 à 24 %,Maison,[2010 - 2020),Option=2 ACH50,>= 2013,Electricite,Electrique,Plinthes électriques,Murale,Electrique

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,year_built,geometry_unit_num_bedrooms,...,heat_pump_heating_capacity_retention_fraction,heat_pump_heating_capacity_retention_temp,heat_pump_is_ducted,heat_pump_cooling_compressor_type,heat_pump_compressor_lockout_temp,misc_plug_loads_vehicle_annual_kwh,misc_plug_loads_vehicle_usage_multiplier,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,750,1940,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,326,apartment unit,8,0.5556,1138,1940,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Saguenay-Bagotville.AP-CFB.Bagotv...,True,-5,1,single-family detached,8,1.8000,1698,1985,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,2005,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,3,apartment unit,8,0.5556,750,1940,2,...,0.5,-15.0,false,variable speed,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,6,apartment unit,8,0.5556,750,1975,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,1940,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,1228,1940,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,2005,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,3750,2015,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dtale.show(dfargs)

In [8]:
dtale.show(dfHPXML)