In [8]:
import os
import sys

FILE_DIR = os.getcwd()
PROJECT_DIR = os.path.abspath(FILE_DIR+ "/../")  # répertoire supérieur
sys.path.append(PROJECT_DIR)

from utils.Sampler import BuildstockBatchArguments, Sampler
import pandas as pd

In [2]:
SamplerBS = BuildstockBatchArguments()
pd.DataFrame(SamplerBS.dct_housing_characteristics).T[["Dependency", "Option"]]

,Dependency,Option
geometry attic type,{},{'Option=Vented Attic': 'Vented Attic'}
geometry_building_num_units,{'Dependency=Type_Logement': 'Type_Logement'},"{'Option=4': '4', 'Option=14': '14', 'Option=1..."
Geometry Wall Exterior Finish,{},{'Option=None': 'None'}
HVAC Has Shared System,{},{'Option=None': 'None'}
HVAC Heating Efficiency,{'Dependency=Source_Energie_Chauf': 'Source_En...,"{'Option=Electric Baseboard, 100% Efficiency':..."
Infiltration,"{'Dependency=Type_Logement': 'Type_Logement', ...","{'Option=1 ACH50': '1 ACH50', 'Option=2 ACH50'..."
Insulation Ceiling,"{'Dependency=Type_Logement': 'Type_Logement', ...","{'Option=QC_R19.6': 'QC_R19.6', 'Option=QC_R24..."
Insulation Foundation Wall,{'Dependency=An_Construction': 'An_Construction'},"{'Option=QC_Wall-R10.1, interior': 'QC_Wall-R1..."
Insulation Wall,"{'Dependency=Type_Logement': 'Type_Logement', ...",{'Option=QC_WoodStud-R14.5': 'QC_WoodStud-R14....
Windows,"{'Dependency=Type_Logement': 'Type_Logement', ...","{'Option=Double, Clear, Metal, Air': 'Double, ..."

In [6]:
d = {}
for key, item in SamplerBS.dct_housing_characteristics.items():
    d[key] = {"Dependance": list(item.get("Dependency").values()),
              "Option": list(item.get("Option").values())}

df = pd.DataFrame(d).T
df.to_csv("./SamplerBS.csv", sep=";")

In [44]:
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/BayesianNetwork/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

# List of node names and their values
lst_NOEUD = InsClsSampler.lst_NOEUD
LIST_Dict = InsClsSampler.LIST_Dict
LIST_Dict

dd = {}
for key, item in LIST_Dict.items():
    dd[key] = {"Dependance": [],
              "Option": list(item.values()),}

for arc in InsClsSampler.bn.arcs():
    src = InsClsSampler.bn.variable(arc[0]).name()
    dest = InsClsSampler.bn.variable(arc[1]).name()
    dd[dest]["Dependance"].append(src)

ddf = pd.DataFrame(dd).T
ddf.to_csv("./SamplerBN.csv", sep=";", encoding="latin-1")
ddf

,Dependance,Option
An_Construction,[Type_Logement],"[< 1950, [1950 - 1960), [1960 - 1970), [1970 -..."
Chauffage_Logement,"[Source_Energie_Chauf, Type_Logement]","[Plinthes électriques, Unités convecteurs, pla..."
Climatisation,"[Type_Logement, Chauffage_Logement]","[Aucune, Fenêtre, mobile, portable, Murale, Ce..."
Mode_Occupation,[Type_Logement],"[Locataire, Proprietaire]"
Nombre_Etages,"[Territoire_HQ, Type_Logement]","[Un étage, Deux étages, Trois étages et plus]"
Nombre_Personnes,[Nombre_Pieces],"[1, 2, 3, 4, 5 et plus]"
Nombre_Pieces,"[Nombre_Etages, Type_Logement]","[1, 2, 11, 12, 13, 14, 15 et plus, 3, 4, 5, 6,..."
Presence_Garage,[Type_Logement],"[Pas de Garage, Garage non chauffé, Garage cha..."
Presence_SousSol,"[Nombre_Etages, Type_Logement]","[Sous sol 6 pied, Vide sanitaire moins 6 pieds..."
Source_Energie_Chauf,"[An_Construction, Type_Logement]","[Electricite, Mazout, Gaz naturel, Bi-energie,..."
Superficie_Totale,"[Nombre_Pieces, Type_Logement]","[[1 - 500), [500 - 1000), >= 5000, [1000 - 150..."
Territoire_HQ,[],"[Est et Nord du Québec, Laurentides, Montmoren..."
Type_Logement,[Territoire_HQ],"[Collective, Triplex, Duplex, Maison en rangee..."