In [1]:
import os
import sys
import pandas as pd
import yaml
import numpy as np

current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from utils.Sampler import Sampler, BuildstockBatchArguments, MapHPXML
from builder.EUEMr import Attribut_EUEMr

#from utils.Master_genereBN import Master_genereBN
#from builder.EUEMr import FormatageEUEMr, EUEMr

import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='openpyxl')

In [2]:
#Données BN
with open("../dataStructure/Bn.yml", 'r') as file:
        NOEUD_EUEMr, LIST_Dict, dict_info = yaml.safe_load(file)

#données csv
Bba = BuildstockBatchArguments()
dctcsv_sampler =Bba.dct_housing_characteristics

In [3]:
#Traitement des données csv
for k in dctcsv_sampler.keys():
    dctcsv_sampler[k]["Nom"] = k
    dctcsv_sampler[k]["Échantillonneur"] = "BuildstockBatchArguments"
    dctcsv_sampler[k]["Valeurs"] = list(dctcsv_sampler[k]["Option"].values())
    dctcsv_sampler[k]["Dépendance (parents)"] = list(dctcsv_sampler[k]["Dependency"].values())

for k in dctcsv_sampler.keys():
    dctcsv_sampler[k]["Dépendance (enfants)"] = []
    for kk in dctcsv_sampler.keys():
        if k in dctcsv_sampler[kk]["Dépendance (parents)"]:
            dctcsv_sampler[k]["Dépendance (enfants)"].append(kk)


#Ajout des variables enfant dans le bn provenant des csv

for k in dict_info.keys():
    for kkbn in dctcsv_sampler.keys():
        if k in dctcsv_sampler[kkbn]["Dépendance (parents)"]:
            dict_info[k]["Dépendance (enfants)"].append(kkbn)

pdcsv_sampler = pd.DataFrame(dctcsv_sampler).T
pdcsv_sampler = pdcsv_sampler[["Nom", "Description", "Valeurs", "Dépendance (parents)", "Dépendance (enfants)", "Échantillonneur", "Source"]]#,


pdDescription = pd.DataFrame.from_dict(dict_info).T.set_index("id").sort_index().reset_index()[["id", "Nom", "Description", "Valeurs", "Dépendance (parents)","Dépendance (enfants)", "Échantillonneur", "Source"]]
#pdDescription["Échantillonneur"] = "Réseau Bayesien"
#pdDescription["Source"] = "EUEMR"



Data_description = pd.concat([pdDescription, pdcsv_sampler], axis=0).reset_index(drop=True)

Data_description.to_csv("../dataStructure/Data_description.csv", index=False)

In [4]:
Data_description

,id,Nom,Description,Valeurs,Dépendance (parents),Dépendance (enfants),Échantillonneur,Source
0,0.0,Territoire_HQ,Territoire HQ,"[Est et Nord du Québec, Laurentides, Montmoren...",[],[Region_Administrative],Réseau Bayesien,EUEMR modifié
1,1.0,Region_Administrative,Zone du Québec,"[Bas-Saint-Laurent, Capitale-Nationale, Centre...",[Territoire_HQ],"[Type_Logement, Nombre_Etages, Spa_Presence, P...",Réseau Bayesien,EUEMR modifié
2,2.0,Type_Logement,De quel genre d'habitation s'agit-il?,"[Collective, Triplex, Duplex, Maison en rangee...",[Region_Administrative],"[Type_Batiment, Nombre_Etages, Nombre_Pieces, ...",Réseau Bayesien,EUEMR modifié
3,3.0,Type_Batiment,De quel genre d'habitation s'agit-il?,"[Collective, Plex, Maison]",[Type_Logement],[],Réseau Bayesien,EUEMR modifié
4,4.0,Nombre_Etages,Nombre d'étages habitables dans la résidence (...,"[Un étage, Deux étages, Trois étages et plus]","[Region_Administrative, Type_Logement]","[Nombre_Pieces, Presence_SousSol, Geometry Sto...",Réseau Bayesien,EUEMR modifié
5,5.0,Nombre_Pieces,Nombre de pièces dans la résidence (incluant l...,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Type_Logement, Nombre_Etages]","[Nombre_Personnes, Superficie_Totale]",Réseau Bayesien,EUEMR modifié
6,6.0,Superficie_Totale,Quelle est la superficie TOTALE habitable de v...,"[[1 - 500), [500 - 1000), [1000 - 1500), [1500...",[Nombre_Pieces],[],Réseau Bayesien,EUEMR modifié
7,7.0,Presence_SousSol,Votre résidence comporte-elle un sous-sol ou v...,"[Sous sol 6 pied, Vide sanitaire moins 6 pieds...","[Type_Logement, Nombre_Etages]",[],Réseau Bayesien,EUEMR modifié
8,8.0,Nombre_Personnes,"En vous incluant, combien de personnes habiten...","[1, 2, 3, 4, 5 et plus]",[Nombre_Pieces],[],Réseau Bayesien,EUEMR modifié
9,9.0,Presence_Garage,Avez-vous un garage?,"[Pas de Garage, Garage non chauffé, Garage cha...",[Type_Logement],[],Réseau Bayesien,EUEMR modifié
10,10.0,Mode_Occupation,Quel est votre lien avec ce logement ? En êtes...,"[Locataire, Proprietaire]",[Type_Logement],[],Réseau Bayesien,EUEMR modifié
11,11.0,An_Construction,Année de construction de l'habitation,"[< 1950, [1950 - 1960), [1960 - 1970), [1970 -...",[Type_Logement],"[Source_Energie_Chauf, Infiltration, Windows, ...",Réseau Bayesien,EUEMR modifié
12,12.0,Climatisation,"Parmi les appareils suivants, lesquels utilise...","[Aucune, Fenêtre, mobile, portable, Murale, Ce...","[Type_Logement, Chauffage_Logement]",[],Réseau Bayesien,EUEMR modifié
13,13.0,Source_Energie_Chauf,Principale source d'énergie utilisée pour le c...,"[Electricite, Mazout, Gaz naturel, Bi-energie,...","[Type_Logement, An_Construction]","[ChaufEau_ChaufType, Chauffage_Logement, HVAC ...",Réseau Bayesien,EUEMR modifié
14,14.0,Chauffage_Logement,Système principal de chauffage,"[Plinthes électriques, Unités convecteurs, pla...","[Type_Logement, Source_Energie_Chauf]","[Climatisation, HVAC Heating Efficiency]",Réseau Bayesien,EUEMR modifié
15,15.0,Spa_Presence,Avez-vous un spa à votre résidence?,"[Oui, Non]","[Region_Administrative, Type_Logement]","[Spa_Logement, Spa_Saison, Spa ChaufType]",Réseau Bayesien,EUEMR modifié
16,16.0,Spa_Logement,Le spa est-il à l'intérieur ou à l'extérieur d...,"[Aucun, Exterieur, Interieur]","[Type_Logement, Spa_Presence]",[Spa_Saison],Réseau Bayesien,EUEMR modifié
17,17.0,Spa_Saison,"Avez-vous utilisé votre spa…? (Printemps, été,...","[Aucun, Pas utilisé, Ne sait pas, Toute_Saison...","[Spa_Logement, Spa_Presence]","[Spa_Utilisation_SaisonChaude, Spa_Utilisation...",Réseau Bayesien,EUEMR modifié
18,18.0,Spa_Utilisation_SaisonChaude,Lequel des deux énoncés suivants correspond le...,"[Aucun, Ne sais pas, Constant, Augmentation]",[Spa_Saison],[],Réseau Bayesien,EUEMR modifié
19,19.0,Spa_Utilisation_SaisonFroide,Lequel des deux énoncés suivants correspond le...,"[Aucun, Ne sais pas, Constant, Augmentation]",[Spa_Saison],[],Réseau Bayesien,EUEMR modifié
20,20.0,Piscine_Presence,"Avez-vous une piscine installée en permanence,...","[Oui, Non]","[Region_Administrative, Type_Logement]",[Piscine_Type],Réseau Bayesien,EUEMR modifié
21,21.0,Piscine_Type,De quel type de piscine s'agit-il?,"[Aucun, Hors_Terre, Creusee_Exterieur, Creusee...","[Type_Logement, Piscine_Presence]","[Piscine_Chauffee, Piscine_Minuterie, Piscine_...",Réseau Bayesien,EUEMR modifié
22,22.0,Piscine_Minuterie,Votre filtreur est-il équipé d'une minuterie?,"[Aucun, Oui, Non]",[Piscine_Type],[],Réseau Bayesien,EUEMR modifié
23,23.0,Piscine_Toile,Possédez-vous une toile solaire?,"[Aucun, Oui, Non]",[Piscine_Type],[],Réseau Bayesien,EUEMR modifié
24,24.0,Piscine_Chauffee,Votre piscine est-elle chauffée (autrement que...,"[Aucun, Oui, Non]",[Piscine_Type],[Piscine_ChaufType],Réseau Bayesien,EUEMR modifié
25,25.0,Piscine_ChaufType,De quelle façon est-elle chauffée? (Ensemble d...,"[Aucun, Ne sait pas, Thermopompe, Electrique, ...",[Piscine_Chauffee],[],Réseau Bayesien,EUEMR modifié
26,26.0,Vehicule_Presence,Voiture(s) électrique? (Base totale),"[Aucune_VE_Aucune_VHR, Une_VE_Aucune_VHR, Aucu...","[Region_Administrative, Type_Logement]",[Vehicule_BornePresence],Réseau Bayesien,EUEMR modifié
27,27.0,Vehicule_BornePresence,Disposez-vous d'une borne de recharge reliée à...,"[Aucun, Oui, Non]","[Type_Logement, Vehicule_Presence]",[],Réseau Bayesien,EUEMR modifié
28,28.0,ChaufEau_ChaufType,À quelle source d'énergie votre chauffe-eau fo...,"[Aucun, Ne sait pas, Electrique, Propane, Gaz ...","[Source_Energie_Chauf, ChaufEau_Presence]",[],Réseau Bayesien,EUEMR modifié
29,29.0,ChaufEau_Type,Quelle est la capacité du chauffe-eau?,"[Non definit, Ne sait pas, Chauffe-eau sans ré...","[Type_Logement, ChaufEau_Presence]",[],Réseau Bayesien,EUEMR modifié
30,30.0,ChaufEau_Presence,Le chauffe-eau est central ou uniquement pour ...,"[Aucun, Logement, Central]",[Type_Logement],"[ChaufEau_ChaufType, ChaufEau_Type]",Réseau Bayesien,EUEMR modifié
31,NaN,Geometry Stories,Geometry Stories,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Type_Logement, Nombre_Etages]","[Geometry Building Horizontal Location, Geomet...",BuildstockBatchArguments,
32,NaN,Geometry Building Number Units,Nombre d'unité d'habitation,"[4, 14, 12, 18, 24, 6, 7, 8, 50, 28, 60, 20, 1...",[Type_Logement],[Geometry Building Horizontal Location],BuildstockBatchArguments,
33,NaN,Geometry Building Horizontal Location,Position horizontale de l'habitation,"[Left, Middle, None, Not Applicable, Right]","[Geometry Building Number Units, Geometry Stor...",[],BuildstockBatchArguments,
34,NaN,Geometry Building Level,Position verticale de l'habitation,"[Bottom, Middle, None, Top]","[Type_Logement, Geometry Stories]",[],BuildstockBatchArguments,
35,NaN,Infiltration,Taux d'infiltration d'air,"[1 ACH50, 2 ACH50, 3 ACH50, 4 ACH50, 5 ACH50, ...","[Type_Logement, An_Construction]",[],BuildstockBatchArguments,
36,NaN,Windows,Type de fenêtre,"[Double, Clear, Metal, Air, Double, Clear, Non...","[Type_Logement, An_Construction]",[],BuildstockBatchArguments,
37,NaN,Insulation Wall,Type d'isolation des murs,"[QC_WoodStud-R14.5, QC_WoodStud-R14, QC_WoodSt...","[Type_Logement, An_Construction]",[],BuildstockBatchArguments,
38,NaN,Insulation Ceiling,Type d'isolation du plafond,"[QC_R19.6, QC_R24.6, QC_R27.3, QC_R30.9, QC_R4...","[Type_Logement, An_Construction]",[],BuildstockBatchArguments,
39,NaN,Insulation Foundation Wall,Type d'isolation du mur de fondation,"[QC_Wall-R10.1, interior, QC_Wall-R12, interio...",[An_Construction],[],BuildstockBatchArguments,
40,NaN,Geometry Wall Exterior Finish,Type de revêtement extérieur des murs,[None],[],[],BuildstockBatchArguments,
41,NaN,geometry attic type,Type de grenier,[Vented Attic],[],[],BuildstockBatchArguments,
42,NaN,HVAC Has Shared System,Système de chauffage partagé,[None],[],[],BuildstockBatchArguments,
43,NaN,HVAC Heating Efficiency,Efficacité du système de chauffage,"[Electric Baseboard, 100% Efficiency, Electric...","[Source_Energie_Chauf, Chauffage_Logement]",[],BuildstockBatchArguments,
44,NaN,Spa ChaufType,Type de chauffage du spa,"[none, electric resistance, gas fired, heat pump]",[Spa_Presence],[],BuildstockBatchArguments,

In [5]:
#EUEMr_description
EUEMr_description = {}
found_dicts = []
for attr_name, attr_value in Attribut_EUEMr.__dict__.items():
    if isinstance(attr_value, dict):
        found_dicts.append({**{"Code": attr_name}, **attr_value})
found_dicts
EUEMr_description = pd.DataFrame(found_dicts)[["Code", "Description", "Label", "IdLabel", "Type"]]#
EUEMr_description.to_csv("../dataStructure/EUEMr_description.csv", index=False)
EUEMr_description

,Code,Description,Label,IdLabel,Type
0,QA1,Quel est votre lien avec ce logement ? En êtes...,"[Le propriétaire / Co-propriétaire, Le locatai...","[0, 1]",discrete
1,QA4,De quel genre d'habitation s'agit-il?,"[Immeuble de 4 à 8 appartements, Immeuble de 9...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]",discrete
2,QC1R,Principale source d'énergie utilisée pour le c...,"[Électricité, Gaz naturel, Mazout, Bois seul o...","[0, 1, 2, 3, 4, 5]",discrete
3,CONS_AN,Consommation annuelle d'électricité en kWh,None,None,Double
4,QA6M,Année de construction de l'habitation,None,None,Entier
...,...,...,...,...,...
113,QT2R,Combien avez-vous de voiture(s) 100 % électriq...,"[Aucune, Une, Deux, Trois]","[0, 1, 2, 3]",discrete
114,QT3,Combien avez-vous de voiture(s) électrique(s) ...,"[Aucune, Une, Deux]","[0, 1, 2]",discrete
115,QT3R,Combien avez-vous de voiture(s) électrique(s) ...,"[Aucune, Une, Deux]","[0, 1, 2]",discrete
116,QT2T3,Voiture(s) électrique? (Base totale),"[Ne possède aucune voiture électrique, Possède...","[0, 1, 2, 3]",discrete
117,QT4,Disposez-vous d'une borne de recharge reliée à...,"[Oui, Non]","[0, 1]",discrete