# Main Notebook: Bayesian Network Sampling and HPXML Mapping

This notebook performs the following tasks:<br>
[**1. Load the Bayesian Network**](#1.-Load-the-Bayesian-Network): Load the Bayesian Network from a `.XDSL` file. <br>
[**2. Execute Sampling**](2.-Execute-Sampling): Generate samples based on the Bayesian Network. <br>
[**3. Add Additional Variables**](#3.-Add-Additional-Variables): Add variables that are not part of the Bayesian Network. <br>
[**4. Map to HPXML Arguments**](#4.-Map-to-HPXML-Arguments): Map the sampled data to HPXML arguments. <br>
[**5. Save Results**](#5.-Save-Results): Save the results to CSV files for further processing. <br>

In [3]:
# importation of packages
import os
import sys
import pandas as pd
import dtale

current_dir = os.getcwd()
PROJECT_DIR = os.path.abspath(current_dir+ "/../")
sys.path.append(PROJECT_DIR)

from src.utils.sampler.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

## **1. Load the Bayesian Network**

In [4]:
# Chargement du BN
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/processed/bayesian_network/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

## **2. Execute Sampling**

In [5]:
Nombre_de_Samples = 100
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)

## **3. Add Additional Variables**

In [6]:
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

## **4. Map to HPXML Arguments**

In [7]:
# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)

Nombre d'attributs HPXML:  131

## **5. Save Results**

In [8]:
dfargs.to_csv(PROJECT_DIR+"/data/output/building-input.csv", index=False)
dfHPXML.to_csv(PROJECT_DIR+"/data/output/building-test.csv", index=False)

dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)
display(dfargs)
display(dfHPXML)

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Geometry Wall Exterior Finish,geometry attic type,...,Eclairage_LED,Type_Batiment,An_Construction,Infiltration,An_ConstructionCode,Source_Energie_Chauf,Cuisiniere_Energie,Chauffage_Logement,Climatisation,ChaufEau_ChaufType
0,1,1,Not Applicable,None,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,Vented Attic,...,Plus de 50 %,Maison,[1970 - 1980),Option=6 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,Aucune,Electrique
1,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",None,Vented Attic,...,0%,Maison,[1960 - 1970),Option=15 ACH50,[1946 - 1971),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique
2,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",None,Vented Attic,...,Plus de 50 %,Maison,[1970 - 1980),Option=15 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,Centrale,Electrique
3,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,0%,Maison,[2000 - 2010),Option=4 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,Centrale,Electrique
4,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,Vented Attic,...,25 à 50 %,Maison,>= 2020,Option=1 ACH50,>= 2013,Electricite,Electrique,Plinthes électriques,Aucune,Electrique
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,1,Not Applicable,None,"Single, Clear, Non-metal",QC_WoodStud-R14.5,QC_R19.6,"QC_Wall-R10.1, interior",None,Vented Attic,...,0%,Maison,< 1950,Option=10 ACH50,< 1946,Bi-energie,Electrique,Thermopompe et Système central à air chaud,Centrale,Electrique
96,9,326,Middle,Bottom,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.6,QC_R18.3,"QC_Wall-R12, interior",None,Vented Attic,...,Plus de 50 %,Collective,[1960 - 1970),Option=8 ACH50,[1946 - 1971),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique
97,1,1,Not Applicable,None,"Double, Clear, Metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,25 à 50 %,Maison,[2000 - 2010),Option=5 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,Aucune,Electrique
98,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",None,Vented Attic,...,Plus de 50 %,Maison,[1980 - 1990),Option=7 ACH50,[1971 - 1986),Bois,Electrique,Fournaise ou poêle à bois et Plinthes électriques,Aucune,Electrique
99,1,1,Not Applicable,None,"Double, Clear, Non-metal, Air",QC_WoodStud-R14.5,QC_R19.6,"QC_Wall-R10.1, interior",None,Vented Attic,...,25 à 50 %,Maison,< 1950,Option=15 ACH50,< 1946,Electricite,Electrique,Plinthes électriques,Aucune,Electrique

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,year_built,geometry_unit_num_bedrooms,...,door_area,heat_pump_is_ducted,heat_pump_compressor_lockout_temp,heat_pump_cooling_compressor_type,overhangs_front_depth,overhangs_front_distance_to_top_of_window,heat_pump_heating_capacity_retention_fraction,heat_pump_heating_capacity_retention_temp,misc_plug_loads_vehicle_annual_kwh,misc_plug_loads_vehicle_usage_multiplier
0,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1698,1975,4,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,1965,5,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1228,1975,3,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,5587,2005,3,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020s_CAN_QC_Saguenay-Bagotville.AP-CFB.Bagotv...,True,-5,1,single-family detached,8,1.8000,1228,2020,3,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,1698,1940,4,...,20,true,10.4,single stage,NaN,NaN,NaN,NaN,NaN,NaN
96,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,326,apartment unit,8,0.5556,1682,1965,2,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1698,2005,4,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1228,1985,3,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,1940,4,...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dtale.show(dfargs)

:

In [ ]:
dtale.show(dfHPXML)

: