# Main Notebook: Bayesian Network Sampling and HPXML Mapping

This notebook performs the following tasks:<br>
[**1. Load the Bayesian Network**](#1.-Load-the-Bayesian-Network): Load the Bayesian Network from a `.XDSL` file. <br>
[**2. Execute Sampling**](2.-Execute-Sampling): Generate samples based on the Bayesian Network. <br>
[**3. Add Additional Variables**](#3.-Add-Additional-Variables): Add variables that are not part of the Bayesian Network. <br>
[**4. Map to HPXML Arguments**](#4.-Map-to-HPXML-Arguments): Map the sampled data to HPXML arguments. <br>
[**5. Save Results**](#5.-Save-Results): Save the results to CSV files for further processing. <br>

In [1]:
# importation of packages
import os
import sys
import pandas as pd
import dtale

current_dir = os.getcwd()
PROJECT_DIR = os.path.abspath(current_dir+ "/../")
sys.path.append(PROJECT_DIR)

from src.utils.sampler.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

## **1. Load the Bayesian Network**

In [2]:
# Chargement du BN
path = PROJECT_DIR+"/data/processed/bayesian_network/BN_EUEMr.XDSL"
InsClsSampler = Sampler(path)
#InsClsSampler.Load_BN(path)

## **2. Execute Sampling**

In [3]:
Nombre_de_Samples = 200
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.GUM_Sampling(Nombre_de_Samples, evs = Evidence)

## **3. Add Additional Variables**

In [4]:
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
#Bba = BuildstockBatchArguments()
lst_dct_args2 = InsClsSampler.resstock_args_sampling(lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

In [5]:
#Tconsignes_chauffage_H1
lst_dct_args2

[{'Geometry Stories': 1,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Single, Clear, Metal',
  'Insulation Wall': 'QC_WoodStud-R17.2',
  'Insulation Ceiling': 'QC_R27.3',
  'Insulation Foundation Wall': 'QC_Wall-R14.4, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'ASHP, SEER 10, 6.2 HSPF',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 6.7',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,22,17)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '16',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour10',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour15',
  'Orientation': 'Northwest',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'None',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'No',
  'Roof Material': 'Metal, Dark',
  'Tconsignes_chauffage_H1': 4.1175476126052475,
  'Tconsignes_chauffage_H2': 5.732249435615148,
  'Tconsignes_chauffage_H3': 16.607638390354232,
  'Tconsignes_chauffage_H4': 20.1716621994405},
 {'Geometry Stories': 1,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 17.6',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,20,20)',
  'Cooling Setpoint': '22',
  'Garage Heating Setpoint': '11',
  'Basement Heating Setpoint': '21',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour19',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour20',
  'Orientation': 'East',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'None',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'No',
  'Roof Material': 'Asphalt Shingles, Medium',
  'Tconsignes_chauffage_H1': 5.0659139087756095,
  'Tconsignes_chauffage_H2': 7.371968072811824,
  'Tconsignes_chauffage_H3': 17.01630435502316,
  'Tconsignes_chauffage_H4': 23.418824957420206},
 {'Geometry Stories': 15,
  'Geometry Building Number Units': 326,
  'Geometry Building Horizontal Location': 'Middle',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R24.5',
  'Insulation Ceiling': 'QC_R41',
  'Insulation Foundation Wall': 'QC_Wall-R17, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'MSHP, SEER 25, 12.7 HSPF',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 15.9',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,17)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '18',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour21',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour21',
  'Orientation': 'Northeast',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'None',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': '2ft R10 Perimeter, Vertical',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'None',
  'Roof Material': 'Asphalt Shingles, Medium',
  'Tconsignes_chauffage_H1': 5.460459483399735,
  'Tconsignes_chauffage_H2': 8.707433714804244,
  'Tconsignes_chauffage_H3': 16.271666284649868,
  'Tconsignes_chauffage_H4': 22.025930006287695},
 {'Geometry Stories': 1,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Low-E, Non-metal, Air, L-Gain',
  'Insulation Wall': 'QC_WoodStud-R14',
  'Insulation Ceiling': 'QC_R24.6',
  'Insulation Foundation Wall': 'QC_Wall-R12, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Fuel Boiler, 72% AFUE & Electric Furnace, 100% AFUE',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 15.9',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(19,19,19)',
  'Cooling Setpoint': '22',
  'Garage Heating Setpoint': '15',
  'Basement Heating Setpoint': '16',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour22',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour16',
  'Orientation': 'West',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'None',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'No',
  'Roof Material': 'Asphalt Shingles, Medium',
  'Tconsignes_chauffage_H1': 6.251379799882677,
  'Tconsignes_chauffage_H2': 7.638274575411778,
  'Tconsignes_chauffage_H3': 17.910802729162498,
  'Tconsignes_chauffage_H4': 22.99573201489024},
 {'Geometry Stories': 1,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Unvented Crawlspace',
  'Windows': 'Double, Low-E, L-Gain',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'MSHP, SEER 17, 9.5 HSPF',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,22,18)',
  'Cooling Setpoint': '20',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour8',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour9',
  'Orientation': 'Southeast',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'None',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'None',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'No',
  'Roof Material': 'Composition Shingles',
  'Tconsignes_chauffage_H1': 3.5819617592955204,
  'Tconsignes_chauffage_H2': 6.740009568187769,
  'Tconsignes_chauffage_H3': 18.538596048994787,
  'Tconsignes_chauffage_H4': 22.812172164164124},
 {'Geometry Stories': 2,
  'Geometry Building Number Units': 2,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Top',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R12.2',
  'Insulation Ceiling': 'QC_R12.5',
  'Insulation Foundation Wall': 'QC_Wall-R10.1, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 19.9',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,22,22)',
  'Cooling Setpoint': '22',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '21',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour1',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour7',
  'Orientation': 'Southwest',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'Uninsulated',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'None',
  'Roof Material': 'Tile, Clay or Ceramic',
  'Tconsignes_chauffage_H1': 4.842397709993952,
  'Tconsignes_chauffage_H2': 6.859400580912675,
  'Tconsignes_chauffage_H3': 15.727433978180077,
  'Tconsignes_chauffage_H4': 23.6419120038751},
 {'Geometry Stories': 2,
  'Geometry Building Number Units': 2,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Bottom',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R18.9',
  'Insulation Ceiling': 'QC_R29.8',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 15.9',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,22,22)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour0',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour17',
  'Orientation': 'North',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'Uninsulated',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'None',
  'Roof Material': 'Metal, Dark',
  'Tconsignes_chauffage_H1': 5.027592468290971,
  'Tconsignes_chauffage_H2': 7.442762219110925,
  'Tconsignes_chauffage_H3': 17.564754553905377,
  'Tconsignes_chauffage_H4': 21.03213330884978},
 {'Geometry Stories': 21,
  'Geometry Building Number Units': 116,
  'Geometry Building Horizontal Location': 'Left',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R24.5',
  'Insulation Ceiling': 'QC_R41',
  'Insulation Foundation Wall': 'QC_Wall-R17, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'EF 21.9',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(20,20,20)',
  'Cooling Setpoint': '21',
  'Garage Heating Setpoint': '16',
  'Basement Heating Setpoint': '20',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour19',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour19',
  'Orientation': 'South',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': '2ft R5 Under, Horizontal',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'None',
  'Roof Material': 'Asphalt Shingles, Medium',
  'Tconsignes_chauffage_H1': 4.1473602643072764,
  'Tconsignes_chauffage_H2': 6.1525543783832095,
  'Tconsignes_chauffage_H3': 14.622135409900494,
  'Tconsignes_chauffage_H4': 21.95347564380648},
 {'Geometry Stories': 1,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 19.9',
  'Refrigerator Extra Efficiency': 'EF 10.2',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(20,18,18)',
  'Cooling Setpoint': '21',
  'Garage Heating Setpoint': '15',
  'Basement Heating Setpoint': '20',
  'Mechanical Ventilation': 'None',
  'Bathroom Spot Vent Hour': 'Hour23',
  'Natural Ventilation': 'Cooling Season, 7 days/wk',
  'Range Spot Vent Hour': 'Hour16',
  'Orientation': 'South',
  'Overhangs': 'None',
  'Vacancy Status': 'Occupied',
  'Has PV': 'No',
  'PV Orientation': 'None',
  'PV System Size': 'None',
  'Battery': 'None',
  'Ceiling Fan': 'Standard Efficiency',
  'Dehumidifier': 'None',
  'Insulation Roof': 'Unfinished, Uninsulated',
  'Insulation Slab': 'None',
  'Interior Shading': 'Summer = 0.7, Winter = 0.85',
  'Radiant Barrier': 'No',
  'Roof Material': 'Asphalt Shingles, Medium',
  'Tconsignes_chauffage_H1': 7.790560057716116,
  'Tconsignes_chauffage_H2': 9.196450562182399,
  'Tconsignes_chauffage_H3': 15.930980792844483,
  'Tconsignes_chauffage_H4': 22.105800787317126},
 {'Geometry Stories': 20,
  'Geometry Building Number Units': 326,
  'Geometry Building Horizontal Location': 'Left',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R24.5',
  'Insulation Ceiling': 'QC_R41',
  'Insulation Foundation Wall': 'QC_Wall-R17, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 17.6',
  'Refrigerator Usage Level': '95% Usage',

## **4. Map to HPXML Arguments**

In [6]:
# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)
#concat dataframe
dfAll = pd.concat([dfargs, dfHPXML], axis=1)
display(dfAll)

Nombre d'attributs HPXML:  206

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Insulation Floor,...,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,schedules_vacancy_period,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,1,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Metal",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15,326,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,Not Applicable,Not Applicable,Unvented Crawlspace,"Double, Low-E, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,14,67,Right,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,2,2,Not Applicable,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,...,10.0,1.0,NaN,NaN,3274.0,NaN,NaN,NaN,NaN,NaN
198,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,4,20,Right,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **5. Save Results**

In [ ]:
dfargs.to_csv(PROJECT_DIR+"/data/output/building-input.csv", index=False)
dfHPXML.to_csv(PROJECT_DIR+"/data/output/building-mapping.csv", index=False)
dfAll.to_csv(PROJECT_DIR+"/data/output/building-test.csv", index=False)

display(dfargs)
display(dfHPXML)
display(dfAll)

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Insulation Floor,...,Eclairage_LED,Type_Batiment,An_Construction,Infiltration,An_ConstructionCode,Source_Energie_Chauf,Cuisiniere_Energie,Chauffage_Logement,Climatisation,ChaufEau_ChaufType
0,1,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Metal",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",Uninsulated,...,Plus de 50 %,Maison,[1970 - 1980),3 ACH50,[1971 - 1986),Electricite,Aucun,Thermopompe et Système central à air chaud,Murale,Electrique
1,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,Ne sait pas,Maison,[1980 - 1990),8 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,Murale,Electrique
2,15,326,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,Ne sait pas,Collective,>= 2020,1 ACH50,>= 2013,Electricite,Electrique,Thermopompe murale et Plinthes électriques,Murale,Electrique
3,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,Plus de 50 %,Maison,[1950 - 1960),10 ACH50,[1946 - 1971),Bois,Aucun,Fournaise ou poêle à bois et Système central à...,"Fenêtre, mobile, portable",Electrique
4,1,1,Not Applicable,Not Applicable,Unvented Crawlspace,"Double, Low-E, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,Plus de 50 %,Maison,[2000 - 2010),6 ACH50,[1986 - 2013),Electricite,Electrique,Thermopompe murale et Plinthes électriques,Murale,Electrique
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,25 à 50 %,Maison,[2000 - 2010),6 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique
196,14,67,Right,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,25 à 50 %,Collective,>= 2020,4 ACH50,>= 2013,Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique
197,2,2,Not Applicable,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,...,25 à 50 %,Plex,< 1950,7 ACH50,< 1946,Electricite,Electrique,Plinthes électriques,Aucune,Electrique
198,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,Plus de 50 %,Maison,[1960 - 1970),8 ACH50,[1946 - 1971),Electricite,Electrique,Thermopompe et Système central à air chaud,Centrale,Electrique
199,4,20,Right,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,0%,Collective,[1980 - 1990),5 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,"Fenêtre, mobile, portable",Electrique

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_orientation,geometry_overhangs_front_depth,geometry_overhangs_front_distance_to_top_of_window,...,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,schedules_vacancy_period,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,2020s_CAN_QC_Saguenay-Bagotville.AP-CFB.Bagotv...,True,-5,1,single-family detached,8,1.8000,315,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,326,apartment unit,8,0.5556,45,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,270,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,135,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,180,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,67,apartment unit,8,0.5556,135,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,2,apartment unit,8,0.5556,45,0,0,...,10.0,1.0,NaN,NaN,3274.0,NaN,NaN,NaN,NaN,NaN
198,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,225,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,20,apartment unit,8,0.5556,180,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Geometry Stories,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,Insulation Wall,Insulation Ceiling,Insulation Foundation Wall,Insulation Floor,...,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,schedules_vacancy_period,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,1,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Metal",QC_WoodStud-R17.2,QC_R27.3,"QC_Wall-R14.4, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15,326,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,Not Applicable,Not Applicable,Unvented Crawlspace,"Double, Low-E, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Low-E, Non-metal, Air, L-Gain",QC_WoodStud-R20.7,QC_R30.9,"QC_Wall-R17.1, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,14,67,Right,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R24.5,QC_R41,"QC_Wall-R17, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,2,2,Not Applicable,Bottom,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R12.2,QC_R12.5,"QC_Wall-R10.1, interior",None,...,10.0,1.0,NaN,NaN,3274.0,NaN,NaN,NaN,NaN,NaN
198,1,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",QC_WoodStud-R14,QC_R24.6,"QC_Wall-R12, interior",Uninsulated,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,4,20,Right,Middle,Slab,"Double, Clear, Non-metal, Air",QC_WoodStud-R18.9,QC_R29.8,"QC_Wall-R17.1, interior",None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dtale.show(dfargs)

In [9]:
dtale.show(dfHPXML)