# Main Notebook: Bayesian Network Sampling and HPXML Mapping

This notebook performs the following tasks:<br>
[**1. Load the Bayesian Network**](#1.-Load-the-Bayesian-Network): Load the Bayesian Network from a `.XDSL` file. <br>
[**2. Execute Sampling**](2.-Execute-Sampling): Generate samples based on the Bayesian Network. <br>
[**3. Add Additional Variables**](#3.-Add-Additional-Variables): Add variables that are not part of the Bayesian Network. <br>
[**4. Map to HPXML Arguments**](#4.-Map-to-HPXML-Arguments): Map the sampled data to HPXML arguments. <br>
[**5. Save Results**](#5.-Save-Results): Save the results to CSV files for further processing. <br>

In [1]:
# importation of packages
import os
import sys
import pandas as pd
import dtale

current_dir = os.getcwd()
PROJECT_DIR = os.path.abspath(current_dir+ "/../")
sys.path.append(PROJECT_DIR)

from src.utils.sampler.Sampler import Sampler, BuildstockBatchArguments, MapHPXML

## **1. Load the Bayesian Network**

In [2]:
# Chargement du BN
InsClsSampler = Sampler()
path = PROJECT_DIR+"/data/processed/bayesian_network/BN_EUEMr.XDSL"
InsClsSampler.Load_BN(path)

## **2. Execute Sampling**

In [3]:
Nombre_de_Samples = 200
Evidence = {}
#Evidence = {"Type_Logement": "Maison en rangee"}
#            "Nombre_Pieces": "1"}#{"Mode_Occupation": "Proprietaire"}

# Exécution de l'échantillonnage
df1 = InsClsSampler.do_Sampling(Nombre_de_Samples, evs = Evidence)

## **3. Add Additional Variables**

In [4]:
lst_dct_args = df1.to_dict(orient='records')
# Affiche les échantillons - Avant enregistrement
#s.getBNStructure()
#print(s.lst_NOEUD, s.LIST_Dict)

#Ajout de varaible hors BN
Bba = BuildstockBatchArguments()
lst_dct_args2 = Bba.sampling( lst_dct_args)

lst_dct_args = [ d2 | d1 for d1, d2 in zip(lst_dct_args, lst_dct_args2)]#lst_dct_args prioritaire

In [5]:
#Tconsignes_chauffage_H1
lst_dct_args2

[{'Geometry Stories': 12,
  'Tconsignes_chauffage_H1': 6.3450353421473435,
  'Tconsignes_chauffage_H2': 6.80085553834448,
  'Tconsignes_chauffage_H3': 17.58265199270265,
  'Tconsignes_chauffage_H4': 23.408872701044103,
  'Geometry Building Number Units': 116,
  'Geometry Building Horizontal Location': 'Left',
  'Geometry Building Level': 'Bottom',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Low-E, Non-metal, Air, L-Gain',
  'Insulation Wall': 'QC_WoodStud-R12.6',
  'Insulation Ceiling': 'QC_R18.3',
  'Insulation Foundation Wall': 'QC_Wall-R14.4, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 6.7',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,21)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '16',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 10,
  'Tconsignes_chauffage_H1': 7.450084442997382,
  'Tconsignes_chauffage_H2': 8.26573092933595,
  'Tconsignes_chauffage_H3': 14.828474769131857,
  'Tconsignes_chauffage_H4': 23.171023667995133,
  'Geometry Building Number Units': 116,
  'Geometry Building Horizontal Location': 'Middle',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R12.6',
  'Insulation Ceiling': 'QC_R18.3',
  'Insulation Foundation Wall': 'QC_Wall-R12, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Wall Furnace, 100% AFUE',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'EF 19.9',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,18)',
  'Cooling Setpoint': '20',
  'Garage Heating Setpoint': '14',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 4.434172624548025,
  'Tconsignes_chauffage_H2': 7.356294104662168,
  'Tconsignes_chauffage_H3': 17.907887498709933,
  'Tconsignes_chauffage_H4': 21.141311151103135,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Triple, Low-E, Non-metal, Air, L-Gain',
  'Insulation Wall': 'QC_WoodStud-R17.2',
  'Insulation Ceiling': 'QC_R27.3',
  'Insulation Foundation Wall': 'QC_Wall-R14.4, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'MSHP, SEER 17, 9.5 HSPF',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 21.9',
  'Refrigerator Extra Efficiency': 'EF 10.2',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(23,23,23)',
  'Cooling Setpoint': '24',
  'Garage Heating Setpoint': '16',
  'Basement Heating Setpoint': '19',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 4.586018260106936,
  'Tconsignes_chauffage_H2': 7.483950818432376,
  'Tconsignes_chauffage_H3': 18.721663426571425,
  'Tconsignes_chauffage_H4': 21.68604599189474,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Single, Clear, Non-metal',
  'Insulation Wall': 'QC_WoodStud-R14',
  'Insulation Ceiling': 'QC_R24.6',
  'Insulation Foundation Wall': 'QC_Wall-R12, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 15.9',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,17)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '18',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 15,
  'Tconsignes_chauffage_H1': 7.662051978296818,
  'Tconsignes_chauffage_H2': 9.507807413079465,
  'Tconsignes_chauffage_H3': 16.69761575130448,
  'Tconsignes_chauffage_H4': 20.700968728670098,
  'Geometry Building Number Units': 183,
  'Geometry Building Horizontal Location': 'Right',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R18.9',
  'Insulation Ceiling': 'QC_R29.8',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 17.6',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(20,20,15)',
  'Cooling Setpoint': '20',
  'Garage Heating Setpoint': '16',
  'Basement Heating Setpoint': '21',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 7,
  'Tconsignes_chauffage_H1': 6.851857811985358,
  'Tconsignes_chauffage_H2': 7.418955070607437,
  'Tconsignes_chauffage_H3': 16.37292971358121,
  'Tconsignes_chauffage_H4': 22.929978127677867,
  'Geometry Building Number Units': 326,
  'Geometry Building Horizontal Location': 'Middle',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Low-E, Non-metal, Air, L-Gain',
  'Insulation Wall': 'QC_WoodStud-R18.9',
  'Insulation Ceiling': 'QC_R29.8',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 17.6',
  'Refrigerator Extra Efficiency': 'EF 15.9',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,19)',
  'Cooling Setpoint': '20',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '20',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 3,
  'Tconsignes_chauffage_H1': 7.520050582407881,
  'Tconsignes_chauffage_H2': 10.70800779818033,
  'Tconsignes_chauffage_H3': 17.642540369809865,
  'Tconsignes_chauffage_H4': 21.65502911528205,
  'Geometry Building Number Units': 3,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Bottom',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R12.6',
  'Insulation Ceiling': 'QC_R18.3',
  'Insulation Foundation Wall': 'QC_Wall-R12, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,22,18)',
  'Cooling Setpoint': '18',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 6.451442216272033,
  'Tconsignes_chauffage_H2': 7.185605636282856,
  'Tconsignes_chauffage_H3': 18.371978672378457,
  'Tconsignes_chauffage_H4': 22.31038965167381,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(18,18,18)',
  'Cooling Setpoint': '22',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '21',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 7.647399151515219,
  'Tconsignes_chauffage_H2': 9.217177122678839,
  'Tconsignes_chauffage_H3': 15.297660090857017,
  'Tconsignes_chauffage_H4': 20.34148634547409,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'MSHP, SEER 29.3, 14 HSPF',
  'Spa ChaufType': 'none',
  'Usage Level': 'High',
  'Cooking Range Usage Level': '120% Usage',
  'Clothes Washer Usage Level': '120% Usage',
  'Clothes Dryer Usage Level': '120% Usage',
  'Refrigerator Efficiency': 'EF 6.7',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '105% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '120% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(21,21,18)',
  'Cooling Setpoint': '19',
  'Garage Heating Setpoint': '15',
  'Basement Heating Setpoint': '20',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 10,
  'Tconsignes_chauffage_H1': 8.682857999698555,
  'Tconsignes_chauffage_H2': 9.85439895737003,
  'Tconsignes_chauffage_H3': 15.310297650105847,
  'Tconsignes_chauffage_H4': 21.94040241021811,
  'Geometry Building Number Units': 326,
  'Geometry Building Horizontal Location': 'Right',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R12.2',
  'Insulation Ceiling': 'QC_R12.5',
  'Insulation Foundation Wall': 'QC_Wall-R10.1, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Baseboard, 100% Efficiency',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 10.5',
  'Refrigerator Extra Efficiency': 'EF 15.9',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(22,22,22)',
  'Cooling Setpoint': '23',
  'Garage Heating Setpoint': '12',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 7.02891323664163,
  'Tconsignes_chauffage_H2': 8.778591668291918,
  'Tconsignes_chauffage_H3': 16.061795889154695,
  'Tconsignes_chauffage_H4': 22.579301885707036,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R17.2',
  'Insulation Ceiling': 'QC_R27.3',
  'Insulation Foundation Wall': 'QC_Wall-R14.4, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Furnace, 100% AFUE',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 10.2',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(18,23,18)',
  'Cooling Setpoint': '21',
  'Garage Heating Setpoint': '10',
  'Basement Heating Setpoint': '17',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 1,
  'Tconsignes_chauffage_H1': 5.46253387725857,
  'Tconsignes_chauffage_H2': 8.746019772658068,
  'Tconsignes_chauffage_H3': 17.885931117783255,
  'Tconsignes_chauffage_H4': 21.131199328525334,
  'Geometry Building Number Units': 1,
  'Geometry Building Horizontal Location': 'Not Applicable',
  'Geometry Building Level': 'Not Applicable',
  'Geometry Foundation Type': 'Heated Basement',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R20.7',
  'Insulation Ceiling': 'QC_R30.9',
  'Insulation Foundation Wall': 'QC_Wall-R17.1, interior',
  'Insulation Floor': 'Uninsulated',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Fuel Furnace, 80% AFUE',
  'Spa ChaufType': 'none',
  'Usage Level': 'Medium',
  'Cooking Range Usage Level': '100% Usage',
  'Clothes Washer Usage Level': '100% Usage',
  'Clothes Dryer Usage Level': '100% Usage',
  'Refrigerator Efficiency': 'EF 21.9',
  'Refrigerator Extra Efficiency': 'None',
  'Refrigerator Usage Level': '100% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '290 Rated kWh',
  'Diswasher Usage Level': '100% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(10,22,21)',
  'Cooling Setpoint': '21',
  'Garage Heating Setpoint': '21',
  'Basement Heating Setpoint': '18',
  'Mechanical Ventilation': 'None'},
 {'Geometry Stories': 4,
  'Tconsignes_chauffage_H1': 4.616654405317997,
  'Tconsignes_chauffage_H2': 5.483245378172909,
  'Tconsignes_chauffage_H3': 14.448086253954095,
  'Tconsignes_chauffage_H4': 22.202041158015017,
  'Geometry Building Number Units': 43,
  'Geometry Building Horizontal Location': 'Right',
  'Geometry Building Level': 'Middle',
  'Geometry Foundation Type': 'Slab',
  'Windows': 'Double, Clear, Non-metal, Air',
  'Insulation Wall': 'QC_WoodStud-R24.5',
  'Insulation Ceiling': 'QC_R41',
  'Insulation Foundation Wall': 'QC_Wall-R17, interior',
  'Insulation Floor': 'None',
  'Geometry Wall Exterior Finish': 'None',
  'geometry attic type': 'Vented Attic',
  'HVAC Has Shared System': 'None',
  'HVAC Heating Efficiency': 'Electric Wall Furnace, 100% AFUE',
  'Spa ChaufType': 'none',
  'Usage Level': 'Low',
  'Cooking Range Usage Level': '80% Usage',
  'Clothes Washer Usage Level': '80% Usage',
  'Clothes Dryer Usage Level': '80% Usage',
  'Refrigerator Efficiency': 'EF 19.9',
  'Refrigerator Extra Efficiency': 'EF 10.2',
  'Refrigerator Usage Level': '95% Usage',
  'Freezer Efficiency': 'EF 12, National Average',
  'Dishwasher Energy': '318 Rated kWh',
  'Diswasher Usage Level': '80% Usage',
  'Lighting Usage Level': '100% Usage',
  'Door Area': '20 ft^2',
  'Door Rvalue': 'Fiberglass',
  'Plug Load': '100%',
  'Heating Setpoint': '(20,18,18)',
  'Cooling Setpoint': '21',
  'Garage Heating Setpoint': '15',

## **4. Map to HPXML Arguments**

In [6]:
# Correspondance HPXML
MapSample = MapHPXML()
lst_dct_HPXML = MapSample.run(lst_dct_args)

#Affichage et enregistrement
print("Nombre d'attributs HPXML: ", len(lst_dct_HPXML[0].keys()))
#display(df1)

dfargs = pd.DataFrame(lst_dct_args)
dfHPXML = pd.DataFrame(lst_dct_HPXML)
#concat dataframe
dfAll = pd.concat([dfargs, dfHPXML], axis=1)
display(dfAll)

Nombre d'attributs HPXML:  158

,Geometry Stories,Tconsignes_chauffage_H1,Tconsignes_chauffage_H2,Tconsignes_chauffage_H3,Tconsignes_chauffage_H4,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,...,heat_pump_cooling_compressor_type,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,12,6.345035,6.800856,17.582652,23.408873,116,Left,Bottom,Slab,"Double, Low-E, Non-metal, Air, L-Gain",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,7.450084,8.265731,14.828475,23.171024,116,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4.434173,7.356294,17.907887,21.141311,1,Not Applicable,Not Applicable,Heated Basement,"Triple, Low-E, Non-metal, Air, L-Gain",...,variable speed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4.586018,7.483951,18.721663,21.686046,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15,7.662052,9.507807,16.697616,20.700969,183,Right,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,5.000542,6.018937,16.161153,20.219451,3,Not Applicable,Top,Slab,"Double, Clear, Non-metal, Air",...,variable speed,10.0,1.0,NaN,NaN,2248.0,NaN,NaN,NaN,NaN
196,15,8.285149,8.911903,15.270554,21.526808,183,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,1,5.151754,5.724904,16.956126,20.842532,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,1,7.127586,9.821836,15.501211,23.692424,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,single stage,NaN,NaN,0.0,991.32487,NaN,NaN,NaN,NaN,NaN
199,1,7.539075,8.600850,16.429706,23.758033,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **5. Save Results**

In [10]:
dfargs.to_csv(PROJECT_DIR+"/data/output/building-input.csv", index=False)
dfHPXML.to_csv(PROJECT_DIR+"/data/output/building-mapping.csv", index=False)
dfAll.to_csv(PROJECT_DIR+"/data/output/building-test.csv", index=False)

##dfHPXML.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-mapping.csv", index=False)
#dfAll.to_csv("N://Mes Documents//Projets LTE//Projet archQc//code//LTE-OPENSTUDIO-CLI//V7 Openstudio 3.7//LTE-OpenStudioCLI-Test//"+"building-test.csv", index=False)

display(dfargs)
display(dfHPXML)
display(dfAll)

,Geometry Stories,Tconsignes_chauffage_H1,Tconsignes_chauffage_H2,Tconsignes_chauffage_H3,Tconsignes_chauffage_H4,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,...,Eclairage_LED,Type_Batiment,An_Construction,Infiltration,An_ConstructionCode,Source_Energie_Chauf,Cuisiniere_Energie,Chauffage_Logement,Climatisation,ChaufEau_ChaufType
0,12,6.345035,6.800856,17.582652,23.408873,116,Left,Bottom,Slab,"Double, Low-E, Non-metal, Air, L-Gain",...,0%,Collective,[1970 - 1980),8 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,Murale,Electrique
1,10,7.450084,8.265731,14.828475,23.171024,116,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,Plus de 50 %,Collective,[1960 - 1970),8 ACH50,[1946 - 1971),Electricite,Electrique,"Unités convecteurs, plancher ou plafond radiant","Fenêtre, mobile, portable",Electrique
2,1,4.434173,7.356294,17.907887,21.141311,1,Not Applicable,Not Applicable,Heated Basement,"Triple, Low-E, Non-metal, Air, L-Gain",...,0%,Maison,[1970 - 1980),8 ACH50,[1971 - 1986),Electricite,Electrique,Thermopompe murale et Fournaise,Murale,Electrique
3,1,4.586018,7.483951,18.721663,21.686046,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,1 à 24 %,Maison,[1950 - 1960),8 ACH50,[1946 - 1971),Electricite,Electrique,Plinthes électriques,Murale,Electrique
4,15,7.662052,9.507807,16.697616,20.700969,183,Right,Middle,Slab,"Double, Clear, Non-metal, Air",...,Ne sait pas,Collective,[1990 - 2000),2 ACH50,[1986 - 2013),Electricite,Electrique,Plinthes électriques,Aucune,Electrique
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,5.000542,6.018937,16.161153,20.219451,3,Not Applicable,Top,Slab,"Double, Clear, Non-metal, Air",...,25 à 50 %,Plex,[1980 - 1990),3 ACH50,[1971 - 1986),Electricite,Electrique,Thermopompe murale et Plinthes électriques,Murale,Electrique
196,15,8.285149,8.911903,15.270554,21.526808,183,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,1 à 24 %,Collective,[1970 - 1980),5 ACH50,[1971 - 1986),Electricite,Electrique,Plinthes électriques,Aucune,Electrique
197,1,5.151754,5.724904,16.956126,20.842532,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,25 à 50 %,Maison,[1960 - 1970),10 ACH50,[1946 - 1971),Electricite,Electrique,Thermopompe et Système central à air chaud,Centrale,Ne sait pas
198,1,7.127586,9.821836,15.501211,23.692424,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,0%,Maison,[1970 - 1980),6 ACH50,[1971 - 1986),Electricite,Electrique,Thermopompe et Système central à air chaud,Centrale,Ne sait pas
199,1,7.539075,8.600850,16.429706,23.758033,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,Plus de 50 %,Maison,< 1950,10 ACH50,< 1946,Electricite,Electrique,Thermopompe et Système central à air chaud,Centrale,Electrique

,weather_station_epw_filepath,simulation_control_daylight_saving_enabled,site_time_zone_utc_offset,geometry_building_num_units,geometry_unit_type,geometry_average_ceiling_height,geometry_unit_aspect_ratio,geometry_unit_cfa,year_built,geometry_unit_num_bedrooms,...,heat_pump_cooling_compressor_type,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,116,apartment unit,8,0.5556,750,1975,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,116,apartment unit,8,0.5556,750,1965,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020s_CAN_QC_Saguenay-Bagotville.AP-CFB.Bagotv...,True,-5,1,single-family detached,8,1.8000,1698,1975,4,...,variable speed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1698,1955,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,183,apartment unit,8,0.5556,2115,1995,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,3,apartment unit,8,0.5556,750,1985,2,...,variable speed,10.0,1.0,NaN,NaN,2248.0,NaN,NaN,NaN,NaN
196,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,183,apartment unit,8,0.5556,1138,1975,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,1228,1965,3,...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,2020s_CAN_QC_Quebec-Lesage.Intl.AP.717140_CWEC...,True,-5,1,single-family detached,8,1.8000,1698,1975,3,...,single stage,NaN,NaN,0.0,991.32487,NaN,NaN,NaN,NaN,NaN
199,2020s_CAN_QC_Montreal-McTavish.716120_CWEC2016...,True,-5,1,single-family detached,8,1.8000,2179,1940,5,...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Geometry Stories,Tconsignes_chauffage_H1,Tconsignes_chauffage_H2,Tconsignes_chauffage_H3,Tconsignes_chauffage_H4,Geometry Building Number Units,Geometry Building Horizontal Location,Geometry Building Level,Geometry Foundation Type,Windows,...,heat_pump_cooling_compressor_type,overhangs_front_depth,overhangs_front_distance_to_top_of_window,permanent_spa_pump_annual_kwh,permanent_spa_heater_annual_kwh,misc_plug_loads_vehicle_annual_kwh,heat_pump_compressor_lockout_temp,geothermal_loop_grout_type,geothermal_loop_pipe_type,simulation_control_ground_to_air_heat_pump_model_type
0,12,6.345035,6.800856,17.582652,23.408873,116,Left,Bottom,Slab,"Double, Low-E, Non-metal, Air, L-Gain",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,7.450084,8.265731,14.828475,23.171024,116,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4.434173,7.356294,17.907887,21.141311,1,Not Applicable,Not Applicable,Heated Basement,"Triple, Low-E, Non-metal, Air, L-Gain",...,variable speed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4.586018,7.483951,18.721663,21.686046,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15,7.662052,9.507807,16.697616,20.700969,183,Right,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,5.000542,6.018937,16.161153,20.219451,3,Not Applicable,Top,Slab,"Double, Clear, Non-metal, Air",...,variable speed,10.0,1.0,NaN,NaN,2248.0,NaN,NaN,NaN,NaN
196,15,8.285149,8.911903,15.270554,21.526808,183,Middle,Middle,Slab,"Double, Clear, Non-metal, Air",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,1,5.151754,5.724904,16.956126,20.842532,1,Not Applicable,Not Applicable,Heated Basement,"Single, Clear, Non-metal",...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,1,7.127586,9.821836,15.501211,23.692424,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,single stage,NaN,NaN,0.0,991.32487,NaN,NaN,NaN,NaN,NaN
199,1,7.539075,8.600850,16.429706,23.758033,1,Not Applicable,Not Applicable,Heated Basement,"Double, Clear, Non-metal, Air",...,single stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dtale.show(dfargs)

In [9]:
dtale.show(dfHPXML)